title: Awesome site
author: [Alex](https://github.com/SukachevAlex)
email: [gmail](sukachevalex@gmail.com)
description: > # this means to ignore newlines until "baseurl:"
 Testing GitHub pages and jekyll

# social links
twitter_username: your-twitter-handle
github_username:  SukachevAlex

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
